//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListaAmigosServiceRef
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Amigo", Namespace="http://schemas.datacontract.org/2004/07/ListaAmigos.Modelos")]
    public partial class Amigo : object
    {
        
        private string AliasField;
        
        private bool EsActivoField;
        
        private string NombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Alias
        {
            get
            {
                return this.AliasField;
            }
            set
            {
                this.AliasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsActivo
        {
            get
            {
                return this.EsActivoField;
            }
            set
            {
                this.EsActivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ListaAmigosServiceRef.IListaAmigosService")]
    public interface IListaAmigosService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListaAmigosService/AgregarAmigo", ReplyAction="http://tempuri.org/IListaAmigosService/AgregarAmigoResponse")]
        System.Threading.Tasks.Task AgregarAmigoAsync(ListaAmigosServiceRef.Amigo amigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListaAmigosService/ObtenerAmigos", ReplyAction="http://tempuri.org/IListaAmigosService/ObtenerAmigosResponse")]
        System.Threading.Tasks.Task<ListaAmigosServiceRef.Amigo[]> ObtenerAmigosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListaAmigosService/BuscarPorAlias", ReplyAction="http://tempuri.org/IListaAmigosService/BuscarPorAliasResponse")]
        System.Threading.Tasks.Task<ListaAmigosServiceRef.Amigo> BuscarPorAliasAsync(string alias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListaAmigosService/CambiarEstado", ReplyAction="http://tempuri.org/IListaAmigosService/CambiarEstadoResponse")]
        System.Threading.Tasks.Task<bool> CambiarEstadoAsync(string alias, bool nuevoEstado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IListaAmigosServiceChannel : ListaAmigosServiceRef.IListaAmigosService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ListaAmigosServiceClient : System.ServiceModel.ClientBase<ListaAmigosServiceRef.IListaAmigosService>, ListaAmigosServiceRef.IListaAmigosService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ListaAmigosServiceClient() : 
                base(ListaAmigosServiceClient.GetDefaultBinding(), ListaAmigosServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IListaAmigosService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ListaAmigosServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ListaAmigosServiceClient.GetBindingForEndpoint(endpointConfiguration), ListaAmigosServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ListaAmigosServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ListaAmigosServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ListaAmigosServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ListaAmigosServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ListaAmigosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task AgregarAmigoAsync(ListaAmigosServiceRef.Amigo amigo)
        {
            return base.Channel.AgregarAmigoAsync(amigo);
        }
        
        public System.Threading.Tasks.Task<ListaAmigosServiceRef.Amigo[]> ObtenerAmigosAsync()
        {
            return base.Channel.ObtenerAmigosAsync();
        }
        
        public System.Threading.Tasks.Task<ListaAmigosServiceRef.Amigo> BuscarPorAliasAsync(string alias)
        {
            return base.Channel.BuscarPorAliasAsync(alias);
        }
        
        public System.Threading.Tasks.Task<bool> CambiarEstadoAsync(string alias, bool nuevoEstado)
        {
            return base.Channel.CambiarEstadoAsync(alias, nuevoEstado);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IListaAmigosService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IListaAmigosService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:63859/ListaAmigosService.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ListaAmigosServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IListaAmigosService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ListaAmigosServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IListaAmigosService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IListaAmigosService,
        }
    }
}
